apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: python-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloPython      
    spec:
      containers:
        - name: py1
          image: "registry.ng.bluemix.net/containers1/py1" # edit here!
          imagePullPolicy: Always
          
---
apiVersion: v1
kind: Service
metadata:
  name: pyHello
spec:
  type: NodePort
  selector:
    app: helloPython
  ports:
   - protocol: TCP
     port: 80
     nodePort: 30080
